const projectsData = [
    {
        id: "meridian",
        title: "Meridian (MMM Platform)",
        category: "AI/ML",
        shortDescription: "Marketing Mix Modeling platform with budget optimization and an LLM-powered analyst interface.",
        fullDescription: "<p>Meridian is a complete end-to-end <strong>Marketing Mix Modeling (MMM)</strong> workspace. It allows stakeholders to upload marketing and outcome data, configure channel mapping, and run budget optimization algorithms.</p><h3>Technical Implementation</h3><ul><li>Implements geometric adstock decay, Hill saturation functions, and OLS/Ridge regression to decompose revenue into channel contributions.</li><li>Engineered a budget optimizer using SciPy SLSQP constrained optimization to recommend optimal channel allocation under diminishing returns.</li><li><strong>Meridian AI:</strong> Built an LLM-powered analyst interface using OpenAI function calling with grounded tool handlers, ensuring all responses cite real model outputs with zero hallucination.</li></ul>",
        techStack: ["React", "TypeScript", "FastAPI", "Scikit-learn", "SciPy", "OpenAI API", "Docker"],
        githubUrl: "https://github.com/Atharva309/Meridian",
        liveUrl: "https://meridian-26kiwy8sz-atharva309s-projects.vercel.app/",
        imageUrl: "", 
        icon: "fas fa-robot"
    },
    {
        id: "jobpilot",
        title: "JobPilot",
        category: "AI/ML",
        shortDescription: "Automated, AI-powered job hunter dashboard using Claude 3.5 Sonnet to semantically match job postings.",
        fullDescription: "<p>A fully automated, AI-powered web dashboard designed to help job seekers bypass manual job board hunting.</p><h3>Technical Implementation</h3><ul><li>Automatically scrapes unstructured company career pages using BeautifulSoup4.</li><li>Engineered a prompt pipeline using <strong>Anthropic's Claude 3.5 API</strong> to evaluate job postings against precise candidate constraints (e.g. visa sponsorship, experience level).</li><li>Manages application states in a centralized UI backed by a robust Neon PostgreSQL database and FastAPI asynchronous endpoints.</li></ul>",
        techStack: ["Claude 3.5 Sonnet", "FastAPI", "PostgreSQL", "BeautifulSoup4", "Render"],
        githubUrl: "https://github.com/Atharva309/JobPilot",
        liveUrl: "https://job-hunter-dashboard-kf6x.onrender.com",
        imageUrl: "", 
        icon: "fas fa-briefcase"
    },
    {
        id: "privacy-guard",
        title: "Privacy-Guard",
        category: "AI/ML",
        shortDescription: "AI-powered PHI redaction for clinical documents using context-aware detection for healthcare compliance.",
        fullDescription: "<p>Privacy Guard automatically detects and redacts <strong>Protected Health Information (PHI)</strong> from clinical documents like discharge summaries, lab reports, and insurance claims.</p><h3>Technical Implementation</h3><ul><li>Utilized the <strong>Apple Vision Neural Engine (M-Series)</strong> for high-precision OCR text extraction.</li><li>Built a two-stage GPT-4o-mini classification pipeline to identify global context and distinguish patient PHI from physician data and clinical codes.</li><li>Engineered a tri-tier visual redaction engine using PyMuPDF to calculate pixel-perfect bounding boxes for document anonymization.</li></ul>",
        techStack: ["GPT-4o-mini", "Apple Vision", "Streamlit", "PyMuPDF", "Python"],
        githubUrl: "https://github.com/Atharva309/Privacy-Guard",
        liveUrl: "",
        imageUrl: "https://raw.githubusercontent.com/Atharva309/Privacy-Guard/main/assets/ui_overview.png",
        icon: "fas fa-shield-alt"
    },
    {
        id: "xai-diabetes",
        title: "Explainable AI in Diabetes",
        category: "AI/ML",
        shortDescription: "Deep learning models for diabetes prediction utilizing SHAP, LIME, and ALE for full interpretability.",
        fullDescription: "<p>Explores diabetes prediction using ML models and XAI techniques on the Pima Indian dataset. Built to ensure AI transparency in critical healthcare environments.</p><h3>Technical Implementation</h3><ul><li>Trained and evaluated deep learning models including Convolutional Neural Networks (CNN), Recurrent Neural Networks (RNN), and Multi-Layer Perceptrons (MLP) using PyTorch.</li><li>Integrated cutting-edge Explainable AI methods: <strong>SHAP</strong> (Shapley Additive exPlanations), <strong>LIME</strong> (Local Interpretable Model-Agnostic Explanations), and <strong>ALE</strong>.</li><li>Extracted and plotted detailed feature importance metrics to mathematically verify why the network outputs specific clinical predictions.</li></ul>",
        techStack: ["Python", "PyTorch", "SHAP", "LIME", "CNN", "RNN"],
        githubUrl: "https://github.com/Atharva309/XAI_diabetes",
        liveUrl: "",
        imageUrl: "https://raw.githubusercontent.com/Atharva309/XAI_diabetes/main/Output/SHAP%20summary%20plots/CNN%20-%20SHAP%20summary.png",
        icon: "fas fa-heartbeat"
    },
    {
        id: "bob-ross-gan",
        title: "Bob Ross Painting GAN",
        category: "AI/ML",
        shortDescription: "Trained a Generative Adversarial Network (GAN) to generate landscape paintings in the style of Bob Ross.",
        fullDescription: "<p>A deep learning project that synthesizes brand new, completely unique landscape paintings mimicking the iconic, calming style of Bob Ross.</p><h3>Technical Implementation</h3><ul><li>Utilized the <strong>Pix2Pix</strong> Generative Adversarial Network (GAN) image-to-image translation architecture.</li><li>Processed and augmented a custom dataset of landscape artwork to train the generator and discriminator network models using PyTorch.</li><li>Optimized adversarial loss functions to translate rough semantic block maps into highly detailed, realistic artistic landscapes.</li></ul>",
        techStack: ["GAN", "Pix2Pix", "PyTorch", "Computer Vision"],
        githubUrl: "https://github.com/Atharva309/BobRoss_Painting_Generator",
        liveUrl: "",
        imageUrl: "https://raw.githubusercontent.com/Atharva309/BobRoss_Painting_Generator/main/output_examples/OUTPUT1.png",
        icon: "fas fa-paint-brush"
    },
    {
        id: "waste-classification",
        title: "Waste Classification AI",
        category: "AI/ML",
        shortDescription: "Classification of waste using image analysis (YOLO, ResNet, MobileNet).",
        fullDescription: "<p>An environmental computer vision pipeline that automatically sorts trash into recycling and waste categories using deep convolutional neural networks.</p><h3>Technical Implementation</h3><ul><li>Applied robust transfer learning across multiple state-of-the-art architectures including <strong>YOLO</strong>, <strong>ResNet</strong>, and <strong>MobileNet</strong>.</li><li>Fine-tuned the networks on custom waste datasets to achieve high real-time inference accuracy and rapid processing speeds.</li><li>Evaluated model precision and bounding box metrics for potential deployment in automated industrial sorting facilities.</li></ul>",
        techStack: ["YOLO", "ResNet", "MobileNet", "Computer Vision"],
        githubUrl: "https://github.com/Atharva309/Waste_Classification",
        liveUrl: "",
        imageUrl: "",
        icon: "fas fa-trash-alt"
    },
    {
        id: "drowsiness-detection",
        title: "Driver Drowsiness Detection",
        category: "AI/ML",
        shortDescription: "Detect drowsiness in drivers through eyes and yawns using YOLOv5.",
        fullDescription: "<p>A real-time computer vision safety system that continuously monitors facial landmarks and yawning patterns to instantly alert drowsy drivers and prevent accidents.</p><h3>Technical Implementation</h3><ul><li>Deployed <strong>YOLOv5</strong> for lightning-fast, real-time object detection and facial bounding box generation.</li><li>Engineered custom OpenCV tracking algorithms to calculate Eye Aspect Ratios (EAR) and mouth opening frequency over temporal frames.</li><li>Built a lightweight, highly robust inference loop capable of running smoothly on embedded edge computing devices inside vehicles.</li></ul>",
        techStack: ["YOLOv5", "Computer Vision", "OpenCV"],
        githubUrl: "https://github.com/Atharva309/Drowsiness_detection_driving",
        liveUrl: "",
        imageUrl: "https://raw.githubusercontent.com/Atharva309/Drowsiness_detection_driving/main/images_outputs/Screenshot%202023-05-21%20at%2011.56.28%20PM.png",
        icon: "fas fa-eye-slash"
    },
    {
        id: "info-carsales",
        title: "INFO-CarSales",
        category: "Data Analytics",
        shortDescription: "Highly interactive vehicle sales dashboard tracking market shifts and dominant brands.",
        fullDescription: "<p>A highly interactive, production-ready Streamlit dashboard built to dynamically track global car sales, dominant auto brands, and core depreciation mechanics.</p><h3>Technical Implementation</h3><ul><li>Engineered dynamic chain-filtering algorithms in Python that automatically sync data context across all visual parameters.</li><li>Built real-time Pandas aggregation logic for parsing Total Sales, Average Price, and Dominant Form Factors instantly.</li><li>Designed a semantic insights engine that dynamically generates natural language business intelligence depending on user-selected filter states.</li></ul>",
        techStack: ["Streamlit", "Python", "Data Visualization", "Pandas"],
        githubUrl: "https://github.com/Atharva309/INFO-CarSales",
        liveUrl: "https://info-carsales-5n9dcu4q94har2hqqbwrye.streamlit.app/",
        imageUrl: "",
        icon: "fas fa-car"
    },
    {
        id: "dashboard-architect",
        title: "Dashboard Architect",
        category: "Data Analytics",
        shortDescription: "Full-stack sales analytics system featuring cursor-based SQL stored procedures and threshold alerts.",
        fullDescription: "<p>A full-stack sales analytics system built on top of a highly optimized PostgreSQL relational database schema, accessible via a responsive Flask web application.</p><h3>Technical Implementation</h3><ul><li>Engineered a custom cursor-based SQL stored procedure and strict <code>AFTER INSERT</code> database triggers to keep monthly sales aggregations automatically up-to-date.</li><li>Integrated dynamic backend CSV ingestion algorithms allowing end users to seamlessly bulk-import new datasets directly into the relational schema.</li><li>Deployed live on Render with robust KPI threshold alerts, chart generation, and fully functioning cloud database routing.</li></ul>",
        techStack: ["Flask", "PostgreSQL", "Python", "SQL"],
        githubUrl: "https://github.com/Atharva309/Dashboard-Architect",
        liveUrl: "https://dashboard-architect.onrender.com/#database",
        imageUrl: "",
        icon: "fas fa-chart-bar"
    },
    {
        id: "asteroid-analysis",
        title: "Asteroid Analysis",
        category: "Data Analytics",
        shortDescription: "Performing Asteroid data analysis using postgresql, liquibase, and R.",
        fullDescription: "<p>A comprehensive statistical analytics pipeline that classifies Near-Earth Objects (NEO) and Potentially Hazardous Asteroids (PHA) using classical machine learning on a structured cloud database.</p><h3>Technical Implementation</h3><ul><li>Conducted extensive data cleaning and feature engineering (including binning critical orbital parameters) directly within complex PostgreSQL queries.</li><li>Maintained strict database versioning, rollout, and schema migrations across environments using <strong>Liquibase</strong>.</li><li>Manually implemented a <strong>Naive Bayes Classifier</strong> algorithm from scratch in R to predict hazardous asteroids based on Semi-major axis, Eccentricity, and Moid distance.</li></ul>",
        techStack: ["R", "PostgreSQL", "Liquibase", "Naive Bayes"],
        githubUrl: "https://github.com/Atharva309/Asteroid-Analysis",
        liveUrl: "",
        imageUrl: "",
        icon: "fas fa-meteor"
    },
    {
        id: "fifa-dashboard",
        title: "FIFA Player Dashboard",
        category: "Data Analytics",
        shortDescription: "Interactive FIFA player analytics dashboard built in PowerBI and Tableau.",
        fullDescription: "<p>An extensive, highly interactive business intelligence dashboard providing deep analytics into FIFA player statistics, geographical market values, and precise attribute distributions.</p><h3>Technical Implementation</h3><ul><li>Engineered advanced <strong>DAX queries</strong> in PowerBI to calculate complex performance metrics, calculated columns, and conditional moving averages.</li><li>Designed highly interactive, user-friendly visual interfaces in Tableau to allow stakeholders multi-dimensional data exploration.</li><li>Optimized underlying data models and relationships to handle large-scale datasets while maintaining sub-second dashboard rendering times.</li></ul>",
        techStack: ["PowerBI", "DAX", "Tableau", "Data Visualization"],
        githubUrl: "https://github.com/Atharva309/FIFA_DASHBOARD",
        liveUrl: "https://app.powerbi.com/view?r=eyJrIjoiZWE0OTg0MDAtNzQzYi00ZjgzLWE3N2EtMzMxNDAyM2U2Y2Q1IiwidCI6ImQxZjE0MzQ4LWYxYjUtNGEwOS1hYzk5LTdlYmYyMTNjYmM4MSIsImMiOjEwfQ%3D%3D",
        imageUrl: "https://raw.githubusercontent.com/Atharva309/FIFA_DASHBOARD/main/Images/1.png",
        icon: "fas fa-futbol"
    },
    {
        id: "car-sales-powerbi",
        title: "Car Sales Dashboard (PowerBI)",
        category: "Data Analytics",
        shortDescription: "Advanced and Interactive Dashboard for Car Sales using PowerBI.",
        fullDescription: "<p>A corporate-grade Business Intelligence dashboard specifically tailored to track automotive sales performance, dealership revenue, and geographic market trends.</p><h3>Technical Implementation</h3><ul><li>Leveraged advanced <strong>PowerBI DAX</strong> functionality to create dynamic time-intelligence measures (e.g. YTD calculations, MoM growth trajectories).</li><li>Designed an intuitive, executive-friendly visualization layout focusing on high-level KPIs, spatial maps, and deep drill-down capabilities.</li><li>Integrated complex multi-source data transformations using Power Query to enforce strict data integrity before visual rendering.</li></ul>",
        techStack: ["PowerBI", "DAX Query", "Data Visualization"],
        githubUrl: "https://github.com/Atharva309/Car-Sales-Dashboard-PowerBI",
        liveUrl: "",
        imageUrl: "https://raw.githubusercontent.com/Atharva309/Car-Sales-Dashboard-PowerBI/main/IMAGES/output1.png",
        icon: "fas fa-car-side"
    },
    {
        id: "cloudsense",
        title: "CloudSense",
        category: "Cloud/Full-Stack",
        shortDescription: "Serverless AI-powered code review platform analyzing GitHub commits using AWS Lambda pipelines.",
        fullDescription: "<p>A highly scalable, serverless AI-powered code review platform that automatically analyzes continuous GitHub commits using webhook-triggered AWS Lambda pipelines and GPT-based review generation.</p><h3>Technical Implementation</h3><ul><li>Designed an event-driven AWS cloud architecture utilizing API Gateway, SQS queues, and Lambda worker functions to process 1,000+ commit events asynchronously.</li><li>Integrated the GPT-4o-mini LLM with FastAPI and PostgreSQL to generate and store structured code-quality findings, security insights, and review histories.</li><li>Deployed the full-stack infrastructure completely on AWS with strict JWT-secured APIs, VPC-connected RDS instances, and an S3-hosted frontend delivery.</li></ul>",
        techStack: ["AWS Lambda", "API Gateway", "SQS", "RDS", "FastAPI", "OpenAI"],
        githubUrl: "https://github.com/Atharva309/CloudSense",
        liveUrl: "",
        imageUrl: "https://raw.githubusercontent.com/Atharva309/CloudSense/main/architecture-diagram.png",
        icon: "fas fa-cloud"
    },
    {
        id: "agentsquared",
        title: "AgentSquared",
        category: "Cloud/Full-Stack",
        shortDescription: "No-code AI agent platform enabling small businesses to create production-ready support and social agents.",
        fullDescription: "<p>A no-code AI agent platform engineered at HackCU 2026, enabling small businesses to create production-ready support and social media agents from standard website URLs or uploaded documents in under 60 seconds.</p><h3>Technical Implementation</h3><ul><li>Engineered a robust FastAPI and SQLAlchemy backend equipped with complex RAG-based (Retrieval-Augmented Generation) knowledge ingestion and asynchronous web crawling.</li><li>Implemented advanced multi-agent workflows handling simultaneous customer support chat, social sentiment monitoring, and autonomous brand posting logic.</li><li>Deployed the end-to-end stack natively on Vultr utilizing Nginx reverse proxies, PM2 process managers, and Ubuntu.</li></ul>",
        techStack: ["FastAPI", "Gemini API", "Next.js", "RAG", "Vultr", "SQLite"],
        githubUrl: "https://github.com/Atharva309/AgentSquared",
        liveUrl: "",
        imageUrl: "",
        icon: "fas fa-project-diagram"
    },
    {
        id: "airline-flutter",
        title: "Airline Reservation App",
        category: "Cloud/Full-Stack",
        shortDescription: "A cross-platform Flutter app for airline reservations.",
        fullDescription: "<p>A complete, robust cross-platform mobile application designed to seamlessly handle complex airline ticket reservations, multi-stop flight searches, and secure user authentication.</p><h3>Technical Implementation</h3><ul><li>Developed the entire client application using the <strong>Flutter framework and Dart</strong>, ensuring fluid, native-level performance on both iOS and Android.</li><li>Implemented highly modular state management and responsive UI/UX principles for an incredibly intuitive mobile navigation experience.</li><li>Integrated robust backend REST API communication logic to fetch live flight schedules, handle tokens, and process secure remote bookings.</li></ul>",
        techStack: ["Flutter", "Dart", "Android Studio", "REST APIs"],
        githubUrl: "https://github.com/Atharva309/AirlineReservation_FlutterApp",
        liveUrl: "",
        imageUrl: "https://raw.githubusercontent.com/Atharva309/AirlineReservation_FlutterApp/main/assets/WhatsApp%20Image%202022-08-23%20at%204.58.55%20PM.jpeg",
        icon: "fas fa-plane"
    },
    {
        id: "airline-web",
        title: "Airline Reservation Web",
        category: "Cloud/Full-Stack",
        shortDescription: "Frontend website for airline reservations.",
        fullDescription: "<p>A highly responsive, dynamic frontend web portal specifically engineered for an airline reservation system, featuring comprehensive flight search, secure user authentication, and interactive visual seat mapping.</p><h3>Technical Implementation</h3><ul><li>Built entirely with Vanilla HTML5, CSS3, and JavaScript to guarantee lightning-fast page load times with absolute zero heavy framework overhead.</li><li>Implemented complex custom DOM manipulation logic for rigorous real-time form validation and highly interactive UI components.</li><li>Designed a deeply accessible, modern user interface that scales and optimizes flawlessly for both widescreen desktop browsers and small mobile devices.</li></ul>",
        techStack: ["HTML", "CSS", "JavaScript", "DOM Manipulation"],
        githubUrl: "https://github.com/Atharva309/airline_reservation_WebPage",
        liveUrl: "",
        imageUrl: "https://raw.githubusercontent.com/Atharva309/airline_reservation_WebPage/main/login.gif",
        icon: "fas fa-globe"
    }
];
